Assistant checkpoint: Add forward declaration to fix conflict
Assistant generated file changes:
- 8_Grafo/Cap6/Operacoes/12_colorirGrafo.h: Add forward declaration of mostrarGrafoColorido

---

User prompt:

Running the code in my project results in the following:

```
In file included from ./8_Grafo/Cap6/GrafoApp.c:3:
In file included from ./8_Grafo/Cap6/Operacoes/../Grafo.h:31:
./8_Grafo/Cap6/Operacoes/13_mostrarGrafocomColoracao.h:7:6: error: conflicting types for 'mostrarGrafoColorido'
void mostrarGrafoColorido(pDGrafo grafo) {
     ^
./8_Grafo/Cap6/Operacoes/12_colorirGrafo.h:52:5: note: previous implicit declaration is here
    mostrarGrafoColorido(grafo);
    ^
1 error generated.
make: *** [Makefile:10: main] Error 1

```

If applicable, propose a fix immediately.