Assistant checkpoint: Add missing function declaration
Assistant generated file changes:
- 8_Grafo/Cap6/Operacoes/12_colorirGrafo.h: Add imprimeVertice function declaration

---

User prompt:

Running the code in my project results in the following:

```
In file included from ./8_Grafo/Cap6/GrafoApp.c:4:
In file included from ./8_Grafo/Cap6/Grafo.h:30:
./8_Grafo/Cap6/Operacoes/12_colorirGrafo.h:51:25: error: use of undeclared identifier 'imprimeVertice'
    mostrarGrafo(grafo, imprimeVertice);
                        ^
1 error generated.
make: *** [Makefile:10: main] Error 1
```

If applicable, propose a fix immediately.